---
_postfix_os_is_supported: true
_postfix_os_is_tested: false

_postfix_default_firewall_type: ufw
_postfix_default_compatibility_level: >-
  {{ ansible_facts.packages.postfix[0].version | regex_replace('^([0-9]+\.[0-9]+)', '\\1') | float }}
_postfix_default_daemon_directory: /usr/lib/postfix/sbin
