---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/install/.aar_doc.yml
      - roles/install/README.md
      - roles/install/meta/argument_specs.yml
      - roles/install/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.postfix'
jobs:
  docs_install:
    name: Generate install role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.postfix
          ref: main
      - name: Generate install role documentation
        working-directory: 'trippsc2.postfix'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/install
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update install role documentation." || /bin/true
          git push origin main
          deactivate
