---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/install/.aar_doc.yml
      - roles/install/README.md
      - roles/install/meta/argument_specs.yml
      - roles/install/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.postfix'
jobs:
  docs_install:
    name: Generate install role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.postfix'
      role_name: 'install'
